### ISSUE TITLE
[Web] Feature: Hide AI names

### ISSUE THREAD

**Issue by MildlyInterested** [OCAP2/OCAP#68] opened 2022-05-30 12:52 UTC
Has been adressed with a new js file but a button would be nice.
https://discord.com/channels/858402673066115102/858454277265555528/964287993475121193

**Comment by indig0fox** [comment] 2022-10-09 20:10
Closing as duplicate of https://github.com/OCAP2/OCAP/issues/54

**Closed as not planned by indig0fox** 2022-10-09 20:10 UTC
Labels: component:web
